#!/usr/bin/python3
print (""" 


                              _                     -                 -  
                             | |                   | |               | |          
  ___ _ __ ___  ___ ______ __| | _____      ___ __ | | ___   __ _  __| | ___ _ __ 
 / __| '_ ` _ \/ __|______/ _` |/ _ \ \ /\ / / '_ \| |/ _ \ / _` |/ _` |/ _ \ '__|
| (__| | | | | \__ \     | (_| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |   
 \___|_| |_| |_|___/      \__,_|\___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|   
                                                                                  

""")

#imports
from tqdm import tqdm
import os
from iterfzf import iterfzf
from selenium import webdriver

# chromium options
options = webdriver.ChromeOptions()
options.add_argument("--headless")
options.add_argument("ignore-certificate-errors")
driver = webdriver.Chrome(options=options)

# username and password Change here !!
user = ""
password = ""

# login in the cms

url = "https://cms.guc.edu.eg/apps/student/CourseViewStn.aspx?id=16&sid=52"
loggin_url = "https://"+user+":"+password+"@" + \
    "cms.guc.edu.eg/apps/student/HomePageStn"+"/1"

# choosing the course *change here!!*
courses = {"Math", "CS", "Circuts", "Physics", "Physics-Lab", "English", "DE"}
course = iterfzf(courses)
Links = {
    "Math": "https://cms.guc.edu.eg/apps/student/CourseViewStn.aspx?id=45&sid=52",
    "CS": "https://cms.guc.edu.eg/apps/student/CourseViewStn.aspx?id=351&sid=52",
    "Circuts": "https://cms.guc.edu.eg/apps/student/CourseViewStn.aspx?id=20&sid=52",
    "Physics": "https://cms.guc.edu.eg/apps/student/CourseViewStn.aspx?id=399&sid=52",
    "Physics-Lab": "https://cms.guc.edu.eg/apps/student/CourseViewStn.aspx?id=398&sid=52",
    "English": "https://cms.guc.edu.eg/apps/student/CourseViewStn.aspx?id=16&sid=52",
    "DE": "https://cms.guc.edu.eg/apps/student/CourseViewStn.aspx?id=33&sid=52"
}
course_url = Links.get(course)

# open the links
driver.get(loggin_url)
driver.get(course_url)

# dir of downloads change here !!
user_home = os.environ["HOME"]
os.chdir(user_home+"/Downloads")

# scrabing download links
download_items = driver.find_elements_by_id("download")
link = []
new_name = []
description = []
for element in tqdm(download_items):
    link.append(element.get_attribute('href'))
    e = element.find_element_by_xpath("../../..")
    new_name.append(e.find_element_by_tag_name("strong").text)
    description.append(e.find_element_by_tag_name("div").text)

item_to_download = iterfzf(description, multi=True)

# Download each item
for i in item_to_download:
    index = description.index(i)
    item_link = link[index]
    file_ext = item_link[-4:]

    if os.path.isfile(new_name[index]+file_ext):
        print("file already exists skipped. ")
        continue

    command = "wget -q --show-progress  --user "+user+" --password "+password + \
        " --no-check-certificate " + "-O \"" + \
        new_name[index]+file_ext + "\" " + item_link
    os.system(command)
